### ISSUE TITLE
POD in the Read*Roles is funky

### ISSUE THREAD

**Issue by demianriccardi** [demianriccardi/HackaMol#10]
need to fix up

**Comment by zmughal** [comment]
Also the links for external resources need to fixed for MetaCPAN:

```perl
=pod

L<Test | http://example.org> # spaces won't work
L<Test|http://example.org> # this works

=cut
```

See the link to the journal article on <https://metacpan.org/pod/HackaMol>.

**Comment by demianriccardi** [comment]
@zmughal++

**Comment by demianriccardi** [comment]
mostly fixed, but Docs are never done.
