### ISSUE TITLE
the HackaMol::Molecule->gt does not set the t attribute 

### ISSUE THREAD

**Issue by sdrasmu12** [demianriccardi/HackaMol#20]
is this the intended behavior?

**Comment by demianriccardi** [comment]
this is tricky.  The gt method is provided by the AtomGroupRole and the t attribute is provided by the PhysVecMVR role.  HackaMol::Molecule consumes both roles, where as another group of atoms (bond, angle, dihedral) does not consume the PhysVecMVR role and does not have t.  

Thus, when a molecule calls the gt method, it changes the t for all atoms, but not itself.  I think gt for Molecule should indeed set the t on itself.

**Comment by demianriccardi** [comment]
After taking a closer look, I think leaving it as it is makes sense.  The t attribute calls gt for a molecule.  So the molecule t method will set itself and all atoms within the molecule. when using molecules use t for everything.  Trying to set t from the gt call will fall into an endless loop of despair.
